name: Demo

on:
  push:
    paths:
      - "demo/**"
      - .github/workflows/demo.yml
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install library dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

      - name: Install demo dependencies
        run: pnpm install
        working-directory: demo

      - name: Build demo site
        run: pnpm build
        working-directory: demo

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/.output/public
